services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_bookings
    ports:
      - "5433:5432"
    volumes:
      - db-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_bookings"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-test-data:
